### ISSUE TITLE
Ms sql driver not supported in workspace

### ISSUE THREAD

**Issue by chkm8** [laradock/workspace#14]
Hi, we have a requirements to use MS Sql as the database and recent updates in laradock includes mssql server but when we do php artisan migrate, it says pdo driver not found, most probably no ms sql driver is installed in the workspace container, so I installed the driver follwing this guide, https://github.com/Microsoft/msphpsql, and I was able to do php artisan migrate. I would wanted to make the installation inside the dockerfile but when I do docker-compose build workspace i got this error(workspace dockerfile is from dockerfile-71).
`Building workspace
Step 1/75 : FROM laradock/workspace:1.3 # placeholder. Need change after new image would be built.
ERROR: Service 'workspace' failed to build: Error parsing reference: "laradock/workspace:1.3 # placeholder. Need change after new image would be built." is not a valid repository/tag: invalid reference format`,

Thanks.

**Comment by Mahmoudz** [comment]
Should be fixed in `v5.3.0`, let me know if not. Thanks.
