### ISSUE TITLE
Request to build new image on Docker Hub

### ISSUE THREAD

**Issue by taufek** [laradock/workspace#19]
Hi,

Any plan to build and push the latest image to Docker Hub?

The last image was pushed 5 months ago and there are few updates already in master.

**Comment by AliveCorpse** [comment]
Done

**Comment by Mahmoudz** [comment]
@taufek I just created the new tags https://hub.docker.com/r/laradock/workspace/builds/ and update the docker files on Laradock https://github.com/laradock/laradock/commit/c2c30bfd0f278f6978a48dc62cf3ee063c9f3efa

Thank you

**Comment by taufek** [comment]
Thank you @Mahmoudz
