### ISSUE TITLE
Tag  code with tag 1.10 or correspondent

### ISSUE THREAD

**Issue by gueroverde** [laradock/workspace#21]
In docker hub need to build a new version of with tag 1.10-72 or 1.9-72 to be used in laradock laradock repository

**Comment by Mahmoudz** [comment]
@gueroverde thanks for notifying me about this. I just created the tag 2.0 for this repo on Github, and I built and triggered builds (2.0-xx) on hub.docker.com now just waiting the queues to get executed, I will update the tags in the Laradock dockerfiles as soon as the builds finishes execution.
