### ISSUE TITLE
[feature] add mysql-client as dependency 

### ISSUE THREAD

**Issue by ayaka209** [laradock/workspace#22]
now we don't have mysql command...

**Comment by UnderDogg** [comment]
maybe duplicate: https://github.com/laradock/laradock/issues/1423
Solution (thanks to https://github.com/laradock/laradock/issues/644):

open up your workspace/Dockerfile and add these lines to it
# mysql-client

`USER root`

`RUN apt update && \
apt install -y mysql-client`
down your containers
`docker-compose down`
then rebuild workspace just by
`docker-compose build workspace`
and re-up you containers for example
`docker-compose up redis nginx mysql`

**Comment by ayaka209** [comment]
I have forked my own copy and made changes but I think it's a very common scenario

Thank you @UnderDogg

**Comment by azaricstefan** [comment]
@ayaka209 I agree with you. 
This should be included in 
1. workspace 
2. php-fpm (_Here only if someone is using it with laravel backpack backup package_)

**Comment by bestlong** [comment]
now can customized install on laradock/laradock .env WORKSPACE_INSTALL_MYSQL_CLIENT.
