### ISSUE TITLE
Please create a tag as `laradock/workspace:2.2-7.3` on dockerhub

### ISSUE THREAD

**Issue by enomotodev** [laradock/workspace#26]
`Dockerfile-73` has been added and `php7.3` has also become GA, so please create a tag as `laradock/workspace:2.2-7.3` on dockerhub

**Comment by sonnygauran** [comment]
![E3088AB3-D852-4F24-85AC-DF67BC58CE9F](https://user-images.githubusercontent.com/188831/62351912-6ee86c80-b539-11e9-893a-26db2c45e8b7.jpeg)

![A6D19750-0FD7-45E6-A88B-085E86AE5AE3](https://user-images.githubusercontent.com/188831/62351913-6f810300-b539-11e9-9df1-cbfc76450d32.jpeg)

![04D0B621-4E10-434A-A3B5-F03F89E41C04](https://user-images.githubusercontent.com/188831/62351914-6f810300-b539-11e9-8978-426ba0f74a59.jpeg)

**Comment by sonnygauran** [comment]
Thanks @Mahmoudz!
