### ISSUE TITLE
`workspace` cannot be run as `linux/arm64` architecture on Apple M1

### ISSUE THREAD

**Issue by gilbok** [laradock/workspace#47]
`workspace` cannot be run as `linux/arm64` architecture on Apple M1.
But `php-fpm` can be run as `linux/arm64` architecture.

```bash
$ docker pull laradock/workspace:latest-7.2

$ docker pull laradock/php-fpm:latest-7.2

$ docker images
REPOSITORY           TAG               IMAGE ID       CREATED        SIZE
laradock/php-fpm     latest-7.2        94e355067b69   2 days ago     410MB
laradock/workspace   latest-7.2        5b0a8a579a35   2 days ago     803MB

$ docker run -it 5b0a8a579a35 uname -m # laradock/workspace:latest-7.2
x86_64

$ docker run -it 94e355067b69 uname -m # laradock/php-fpm:latest-7.2
aarch64
```

I think it is because laradock/workspace is using `phusion/baseimage:0.11` as base image.
And it supports only `linux/amd64`

- https://github.com/laradock/workspace/blob/master/Dockerfile-7.2#L7

```bash
FROM phusion/baseimage:0.11
```

Its recent tags are supporting multi-arch including `linux/arm64` now. 
So the base image needs to be changed to the one which supports `linux/arm64`

<img width="1223" alt="Screen Shot 2021-05-17 at 20 19 01" src="https://user-images.githubusercontent.com/1301040/118496856-b65fdd00-b74e-11eb-9c9f-5d767623c232.png">

**Comment by bestlong** [comment]
base image will adjusted.
